insert into skills values ('Android','Primary', 'Android');
insert into skills values('SAP PI/PO', 'Primary', 'SAP PI/PO');
insert into skills values('UI-UX Designer', 'Primary', 'UI-UX Designer');
insert into skills values('SAP UI5', 'Primary', 'SAP UI5');
insert into skills values('SAP ABAP', 'Primary', 'SAP ABAP');
insert into skills values('Java', 'Primary', 'Java');
insert into skills values('Testing', 'Primary', 'Testing');
insert into skills values('Project Management', 'Primary', 'Project Management');
insert into skills values('SAP PI', 'Secondary', 'SAP PI');	
insert into skills values('UX Designer', 'Secondary', 'UX Designer');	
insert into skills values('SAP UI5', 'Secondary', 'SAP UI5');	
insert into skills values('Android', 'Secondary', 'Android');	
insert into skills values('ABAP OO', 'Secondary', 'ABAP OO');	
insert into skills values('Java', 'Secondary', 'Java');		
insert into skills values('SAP ABAP', 'Secondary', 'SAP ABAP');	
insert into skills values('Webdynpro', 'Secondary', 'Webdynpro');	
insert into skills values('Project Management', 'Secondary', 'Project Management');